export default {
  'da-DK': {
    title: 'Frivillige bidragsydere',
    subtitle: 'En kæmpe tak til alle involverede. Vi kunne ikke have gjort det uden jeres hjælp.',
    services: {
      prefix: 'Og tak til de serviceudbydere, der sponsorerer den infrastruktur og software, vi bygger på:',
      list: [
        '[AWS](https://aws.amazon.com/) for stabil data storage.',
        '[Zeit](http://zeit.co/) for skalerbar hosting.',
        '[GitHub](https://github.com) for versionskontrol.',
        '[Twilio](https://twilio.com/) for en simpel SMS-service.',
        '[Rollbar](https://rollbar.com/) for logging.',
        '[Linear](https://linear.app/) for at organisere samarbejdet.',
        // '[TDC](https://tdc.dk/) for skaleret kommunikation til danskerne',
      ],
    },
    signup: '... og flere følger. [Skriv dig op for at bidrage](https://airtable.com/shrM3SHGwxEnnCChj).',
  },
  'en-UK': {
    title: 'Volunteering Contributors',
    subtitle: "A huge thank you to everyone involved! We couldn't have done it without you.",
    services: {
      prefix: 'And to the service providers who sponsored the infrastructure and software we rely on:',
      list: [
        '[AWS](https://aws.amazon.com/) for reliable data storage.',
        '[Zeit](http://zeit.co/) for scalable hosting.',
        '[GitHub](https://github.com) for version control.',
        '[Twilio](https://twilio.com/) for simple SMS services.',
        '[Rollbar](https://rollbar.com/) for logging.',
        '[Linear](https://linear.app/) for organizing the collaboration.',
        // '[TDC](https://tdc.dk/) for scaled communication to the Danes',
      ],
    },
    signup: '... and expanding. [Sign up to contribute](https://airtable.com/shrM3SHGwxEnnCChj).',
  },
  contributors: [
    'Jesper Theil Thomsen, CEO @ [Soundboks](https://soundboks.com)',
    'Louis Arge, Software Engineer @ [Pelion](https://pelion.app/)',
    'Dominic Parr, Venture Analyst @ [Accelerace](https://www.accelerace.io/)',
    'Martin Krag, Investor @ [byFounders](https://byfounders.vc/)',
    'Carl Kronika, Communication @ [Copus.dk](https://copus.dk/)',
    'Martin Permin, CEO @ [Pelion](https://pelion.app/)',
    'Andreas Olesen, Developer',
    'Aksel Larsen, Partner, [Copenhagen Data](https://copenhagendata.com)',
    'Henrik Teisbæk, CEO / Co-founder @ [veo.co](https://veo.co/), [billetto.dk](https://billetto.dk/) and [bloggersdelight.dk](https://bloggersdelight.dk/)',
    'Sissel Hansen, CEO @ [startupguide.com](https://startupguide.com)',
    'Mikkel Møller Andersen, Senior Consultant @ [Intellishore](https://intellishore.dk/)',
    'Sebastian Winther, Product & Engineering @ [Zetland](https://zetland.dk/)',
    'Rasmus Kolbe, Influencer & Creative Director @ [CUBE](https://wearecube.se/)',
    'Jeppe Rindom, CEO @ [Pleo](https://www.pleo.io/)',
    'Holger Thorup, CTO @ [Pelion](https://pelion.app/)',
    'Emil Bender Lassen, CEO @ [Project Access](https://projectaccess.org)',
    'Mads Damsbo, CEO @ [makropol.dk](https://makropol.dk) and [kasparai.com](https://kasparai.com)',
    'Christian Skovholm, Software Engineer, tidl. @ [Netcompany](https://netcompany.com)',
    'Tristan Homsi, Founder @ [Readwise.io](https://readwise.io)',
    'Jacob Lennheden, CEO @ [Escalino](http://www.escalino.com/) and Former Innovation Lead, [IDA](https://ida.dk/)',
    'Andreas Lønborg, Medical Doctor @ Nykøbing F. Sygehus',
  ],
};
